version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      TD_DB_PATH: /data/td.db
      VERIFIER_URL: http://verifier:3001
    volumes:
      - backend-data:/data
    ports:
      - "8000:8000"
    depends_on:
      - verifier

  verifier:
    build:
      context: .
      dockerfile: backend/verifier/Dockerfile
    ports:
      - "3001:3001"

volumes:
  backend-data:
